# Generated by Django 3.2.8 on 2021-11-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
