# Generated by Django 3.2.8 on 2021-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_child',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
