# Generated by Django 3.2.8 on 2021-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_auto_20211120_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='type_vehicle',
            field=models.CharField(blank=True, choices=[('Select Options', 'Select Options'), ('TOYOTA ETIOS', 'TOYOTA ETIOS'), ('SWIFT DZIRE', 'SWIFT DZIRE'), ('MAHINDRA VERITO', 'MAHINDRA VERITO'), ('INNOVA 6+1', 'INNOVA 6+1'), ('INNOVA 7+1', 'INNOVA 7+1'), ('TEMPO TRAVELLER', 'TEMPO TRAVELLER'), ('MINI BUS', 'MINI BUS'), ('SEDAN', 'SEDAN'), ('HATCHBACK', 'HATCHBACK')], max_length=100, null=True),
        ),
    ]
