# Generated by Django 3.2.8 on 2021-10-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0003_alter_booking_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
    ]
