# Generated by Django 3.2.8 on 2021-10-28 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='amount',
            new_name='subscription_amount',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='order_id',
            new_name='payment_mode',
        ),
        migrations.RenameField(
            model_name='paymentdetails',
            old_name='payment_signature',
            new_name='tranc_id',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='package',
            name='expire_pack',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='registeruser',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='app.registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='package',
            name='membership',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app.package'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
    ]
