# Generated by Django 3.2.8 on 2021-11-15 15:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211115_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='dp_pic',
            new_name='profile_pic',
        ),
        migrations.AlterField(
            model_name='package',
            name='id',
            field=models.IntegerField(default=app.models.generate_id, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='id',
            field=models.IntegerField(default=app.models.generate_id, editable=False, primary_key=True, serialize=False),
        ),
    ]
