# Generated by Django 3.2.8 on 2021-10-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_package_subscription_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='subscription_amount',
            field=models.IntegerField(max_length=100),
        ),
    ]
